### ISSUE TITLE
Add network statistics back in to APIs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#149]
WIP ticket. tldr: Console relies on fields that were in the statistics endpoint to do a few things:
- Show the version of the node you are connected to
- Time if blocks are being slow 

For now I'm just disabling those panels, but some of  them are useful enough that we should bring them back. However, the statistics endpoint was a bit of a catch all endpoint, so we can come up with a better GraphQL structure than we did last time.

https://github.com/vegaprotocol/console/pull/6433 is a PR in console that removes the dependence on the statistics that used to be in core, but to get back some of the functionality this disables we want some fields back.

# Fields that should come back / be added
## Version info
___Versions rationale: We display these in the client, and they have been useful for checking details with users. As we were connected to core, the core node version and tendermint version made sense, I don't mind being told they don't any more.___
- Vega data node software version
- Up for debate: Vega core node version
- Up for debate: Tendermint version

## Block info
__Rationale: `vegaTime` is useful as it is the one absolute we can show people in relation ot their own time__

- `vegaTime`
- Up for debate: `blockDuration`

Untouched details to be filled in:

**Comment by gordsport** [comment]
Closing as this is present
