### ISSUE TITLE
Trade timestamps out of order when querying for trades on a market

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/data-node#15]
# Problem encountered

When querying the Vega API for trades on a particular market (either ascending or descending), we have observed that the timestamps for trades can be out of chronological order. The deterministic sequence ID is still correct and in order however.

# Steps to reproduce

Run the query as follows, see attached log for example with out of chronological order timestamps.

gRPC:
```
marketID := "076BB86A5AA41E3E" 
pagination := api.Pagination{ Descending: false, Skip: uint64(9800), Limit: 50, } 
tradesByMarketReq := api.TradesByMarketRequest{MarketId: marketID, Pagination: &pagination} 
tradesByMarketResp, err := dataClient.TradesByMarket(context.Background(), &tradesByMarketReq) 
fmt.Printf("%+v\n", tradesByMarketResp)
```

GraphQL:
```
query {
  market(id:"076BB86A5AA41E3E") {
   	trades(skip: 9800, first: 50){
      type
      buyOrder
      sellOrder
      createdAt
      id
      size
    }
  }
}
```

# Expected behaviour
Timestamps and IDs should be in either ascending or descending order

# Logs

Attached

# Additional content

From @jeremyletang in Slack:
> Ahh! It’s because of the fact that it uses the time of the agressor  when creating the trade
> Which, depending on how you filter, and the fact that it can be confusing during auction uncrossing, can ben a bit unclear 
> Although still worth looking at how to improve that.
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1624390930496800

# Log files

<img width="583" alt="Screenshot 2021-06-22 at 20 36 35" src="https://user-images.githubusercontent.com/149245/123011921-3bc35680-d3b9-11eb-91b8-806fb5b39c8a.png">

[vega-log.log](https://github.com/vegaprotocol/vega/files/6697919/vega-log.log)

**Comment by gordsport** [comment]
Hey @cdm 
I think this has been resolved in data-nodev2. Running the below query does order these in a chronological order. There is also a current conversation ongoing between @mattrussell36 and @guoguojin regarding the default ordering of the paginated APIs (newest first etc..) 

```
query {
  market(id:"ea5a6b6f56171458f0c862852fe501c26b8ef9cedbd886c5c8f2895f7c766618") {
   	trades(skip: 9800, first: 50){
      type
      buyOrder
      sellOrder
      createdAt
      id
      size
    }
  }
}
```

Can you please check again as I intend to close this issue - thanks

**Comment by cdm** [comment]
Jeremy identified the cause of this bug in v1, so if the code in v2 has been updated to query accurately from Postgres then we should be good to go 🤞

**Comment by gordsport** [comment]
Closing as resolved in data-node v2 and the pagination ordering that @guoguojin is implementing
