### ISSUE TITLE
GraphQL: Withdrawal txHash should be marked as @deprecated if it is decided to get rid of it

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#160]
https://github.com/vegaprotocol/data-node/blob/0d793d240a23fc361188326c7cb9a4214b5295ba/gateway/graphql/schema.graphql#L1622-L1623

GraphQL supports directives, for example https://www.apollographql.com/docs/apollo-server/schema/directives/#default-directives can be used to mark a field as being removed in an upcoming release.

As we head towards a more stable API it will be good to get in to the habit of flagging these things early.

Note: It hasn't been scheduled for removal yet. This is a ticket to sit around until it is decided to remove storing the TX hash.

**Comment by gordsport** [comment]
This was kept so issue can be closed
