### ISSUE TITLE
New data-node only API: configuration?

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#188]
WIP ticket as... this is a terrible name. But

# Background
https://github.com/vegaprotocol/data-node/issues/187 was created, because there *used* to be a network parameter defining the governance asset for the network. This correctly got removed, as the control of that asset is now the concern of the bridge contract deployed for the network.

# Problem
Clients have no way to tell users what the governance asset for a given network is. For [vegaprotocol/console](https://github.com/vegaprotocol/console) & [vegaprotocol/token-frontend](https://github.com/vegaprotocol/token-frontend) that is a problem, as they can connect to multiple environments and networks.

It would be incorrect to have a governance parameter for something that is not changeable in the network, and so we currently have no way to fetch the asset ID / contract address of the governance asset without hardcoding a config, or going to the bridge contract on the relevant Ethereum network, which are either unreliable or messy. So this ticket proposes a new endpoint / GraphQL place to get... information about the network. It's possible this could be in an endpoint that also contains #149. 

# Proposed solution

```graphql

enum NodeType {
  VALIDATOR
  NONVALIDATOR
}

# Returns version information for the infrastructure this API node is connected to
type Version {
  # The version of this data node
  dataNode: string #e.g. 0.44.4
  # The version number of the Vega node this data node is streaming events from
  upstreamNode: string #e.g. 0.44.4
  # The type of node this data node is streaming events from
  upstreamNodeType: NodeType #e.g. VALIDATOR
  # Tendermint version
  consensusVersion: string #e.g. 0.34.3
}

# Contains all status info
type Status {
  # The asset currently used for governance
  governanceAsset: Asset;
  # Version information for this infrastructure
  version: Version;
  # Current vega time
  vegaTime: string;
}

Query {
  status: Status;
}

```

so:
```graphql
{ status { governanceAsset { id name} }
```
Would get me
```json
{ 
  "status": { 
    "governanceAsset": {
      "id": "123345",
     "name": "VEGA (test)"
    }
  }
} 
```

# Notes
- There's a workaround, which is reading the network parameter `rewards.asset`, which is currently, usually, unreliably configured to be the same as the governance asset
- REST could use governanceAssetId, or nest the object, as approriate
- The version strings are a *nice to have*, and could be handled in a separate ticket (#149)

**Comment by gordsport** [comment]
Closing as there is a network parameter defining the governance asset for the network
