### ISSUE TITLE
Not all orders visible via API

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/data-node#19]
Strange case of invisible orders on staging:
UI isn’t showing any of my orders on BTCUSD, market id: `076BB86A5AA41E3E`. I am an LP on the market. 

![image](https://user-images.githubusercontent.com/62546419/114309315-a8c78f80-9ade-11eb-91be-65f1d1020bc8.png)

The script `/get-orders-and-trades/get-orders-and-trades-for-market.py` isn’t showing any orders on the market `076BB86A5AA41E3E` with my partyID:
`eaa2dd789b85c43e8a19c7f11e5124416de43608594008502a40181b85dd90ec`.

In the market data view the best static bid and best static ask are my limit orders since I submitted sell 100 @ 64000 and buy 100 @ 52000 a while back and it's "too far" and "too exact" for the bots:
![image](https://user-images.githubusercontent.com/62546419/114309348-c4cb3100-9ade-11eb-83fa-3744926cdece.png)

For other markets e.g. `1F0BB6EB5703B099` the python script and the UI show my orders. What am I missing?

@jeremyletang 's comment "Hum, I think the api may not like much the fact that it’s creating gazillions of orders with the commitment, we may need to revise that."

**Comment by gordsport** [comment]
To be re-tested once we have data-nodeV2 on stagnet

**Comment by gordsport** [comment]
Closing pending this issue being reported in the new APIs and console
