### ISSUE TITLE
Improve API test robustness

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/data-node#213]
Given the asynchorous nature of the tests in `package api_test` A `time.Sleep()` is used to ensure events are received and processed in the necessary order (see `testutils_test.go/PublishEvent`). This is not ideal and should be made more robust.

What is needed is functionality in the broker that, after calling `b.Send()`, allows the caller to wait until this event has been processed by all subscribers. In terms of these test specifically, we need to be sure that the test-event has been pushed before we send a subsquent time-event to flush them.

**Acceptance Criteria**
- The `time.Sleep()` is removed from `PublishedEvents`
- The tests are shown to remain stable

**Comment by gordsport** [comment]
@wwestgarth 
Can you let me know if this is still required? If so I will move to vega repo

**Comment by wwestgarth** [comment]
Not really. I'm not even sure the test this refers to exist anymore since all the data-node V2 stuff.
