### ISSUE TITLE
Create an event / API for raw Position from the core

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/data-node#23]
At the moment the Position API rely on events to build up the openVolume of the party and PNL.
We need a new event, which would be send every time a position hold by the Position engine is being updated, using this we could build an accurat eview of all information from a Position in a give market for any traders.

Mostly I'm thinking of the following fields which without this are never expose / accessible outside of the core:
-  Potential volume (orders not yet accepted/rejected):  buy, sell int64
-  Volume weighted buy/sell price: vwBuyPrice, vwSellPrice uint64

### Acceptance Criteria:

When a new trader places a buy/sell order for any volume, and there are no resulting trades, the positions plugin should return 0 for the position size (actual positions held), but their potential buy position should be the size of the order that was just placed.

If the trader places 2 buy/sell orders (e.g. buy 5 @ 10, then buy 5 @ 20), the vwBuyPrice should be 15 [`(5*10 + 5*20)/10`]

A scenario:

Trader places 3 orders:

buy 10 @ 100    => results in 1 trade of 5 @ 100
buy 5 @ 130      => results in 3 trades: 2 @ 110, 1 @ 120, 2 @ 130
sell 15 @ 150    => No trades

The positions API should return the following information for this trader:

Long: 10 (4 trades of sizes 5, 2, 1, and 2)
Short: 0 (no sell trades)
Position therefore will be +10

Potential long: 5 (buy 10 @100 only traded 5, so half of the order is still on the book)
Potential short: 15 (sell order still on the book)

vwBuy: 110 [`(5*100+2*110+120+2*130)/(5+2+1+2) = 1100/10 = 110`]
vwSell: 0 (no sell trades made)

**Comment by gordsport** [comment]
Hey @peterbarrow 
Do you know if you have implemented this already or if we need to reschedule this work?

**Comment by gordsport** [comment]
Closing as this has been implemented, if other updates are needed this can come in a new issue in the vega repo
