### ISSUE TITLE
Distinguish between valid/invalid partyIDs

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/data-node#259]
Depends on vegaprotocol/vega#1616. Replaces vegaprotocol/vega#1622.

Once the format of `partyID` has settled down, add API validation such that:
* an API call involving a valid-but-not-yet-seen `partyID` does **not** return an error
* an API call involving an invalid `partyID` **does** return an error

Note: It is not relevant whether a valid `partyID` has been seen before or not.

**Comment by gordsport** [comment]
Closing as we have added validation for Vega public keys
