### ISSUE TITLE
Improve market API to handle expired markets better

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#264]
@ashleyvega’s solution below is better than this suggestion, so while the ticket is still valid, the implementation shouldn’t follow the original suggestion, which I’ve left struck out. ~Follows vegaprotocol/vega#1915. Now that expired markets don't return `null`, but return a market object, we have to update the API to allow us to query for only open markets.~

~Proposal: add a new parameter,`includeExpired`, that defaults to `false`. When set to true, expired markets are included.~

**Comment by gordsport** [comment]
closing as a dupe:
- https://github.com/vegaprotocol/data-node/issues/264
