### ISSUE TITLE
Improve GraphQL error message for InvalidArgument, missing pagination 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/data-node#272]
# Problem encountered
We got a request to improve an error message that comes up in GraphQL. bitcoinbill ran a query, forgot to specify pagination on orders and received an error, which he said was not helpful enough. `{ "message": "input: InvalidArgument error", "path": [ "parties", 21, "orders" ] }`

# System response
 `{ "message": "input: InvalidArgument error", "path": [ "parties", 21, "orders" ] }`

**System version:** Specify the system version (0.xx.xx)
**Protocol:** Specify the protocol
- [ ] gRPC
- [ ] REST
- [x] GraphQL

**Component:** Specify the components that might be related
- [x] [Vega](https://github.com/vegaprotocol/vega/)
- [ ] [Tendermint](https://github.com/tendermint/tendermint)
- [ ] [Console](https://github.com/vegaprotocol/console/)
- [ ] [Ethereum Bridge](https://github.com/vegaprotocol/Event_Queue)
- [ ] [Vega Wallet](https://github.com/vegaprotocol/go-wallet/)

# Expected behaviour
An error message that helps the user more easily troubleshoot what went wrong.

**Comment by gordsport** [comment]
Closing - pending reports of similar issues with API v2s
