### ISSUE TITLE
Subscriptions to none existent markets (and parties)

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/data-node#30]
We have had a suggestion from a Discord user surrounding subscriptions on GraphQL (and probably gRPC):

> I've just noticed that I can create WS subscriptions to parties / markets that don't exist. I wonder if you want to reject these requests to protect the network from being susceptible to spam (unless of course you're silently rejecting them already). 

@barnabee suggested early on that we do not return "Party does not exist" errors for unknown parties, so not sure on the parties front myself and worth checking.

For markets that don't exist, it seems plausible to me that we would close the sub with an error that the market is not found on Vega. Again worth checking 👍

**Comment by gordsport** [comment]
you may want to subscribe to a subscription before a party or market exists - closing for now
