### ISSUE TITLE
Discussion: API: Could we return the time priority for an order?

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#31]
While discussing [Auction Mode UI](https://github.com/orgs/vegaprotocol/projects/47) we realised that we could calculate if your order will match, if we knew your price level and your time prioirity within that level. We get the first piece of information - could we get the second?

This isn't an urgent request, and it's likely to be a 'no', as this would be changing continuously. But it would be useful.

**Comment by gordsport** [comment]
Closing as for now we not not have plans to implement this feature
