### ISSUE TITLE
API to get all transaction details in/out of account 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#32]
Similar to  vegaprotocol/vega#1953, but for internal transfers. We want to be able to [show what a user has earned from Maker fees](https://github.com/orgs/vegaprotocol/projects/11#card-45025199), which isn't currently possible.

REST proposal:
https://n04.d.vega.xyz/parties/aef0f72ec9fd2f1990e483ad51604268b5d701b24f3d46fac3f8dae3b4ae9449/accounts/aef0f72ec9fd2f1990e483ad51604268b5d701b24f3d46fac3f8dae3b4ae9449/transfers

```typescript
{
   from: 'account_id',
   to: 'account_id',
   reason: 'string',
   amount: number,
   asset: asset
}
```

**Comment by gordsport** [comment]
There has now been implemented APIs for internal transfers - does this suffice for this issue?

**Comment by edd** [comment]
I'll go and take a look

**Comment by edd** [comment]
@gordsport Technically, yes. But the API design is quite different to this request, which was for transfers being a nested property of party, and the parameter 'pubkey' is inconsistent and incorrect. Where should I raise some bugs for someone to review the API with someone from @vegaprotocol/frontend?
