### ISSUE TITLE
API Feature request: Show Realised PnL for each trader on a trade

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/data-node#33]
To return what effect that trade had on both parties realised PnL. So the difference between the realisedPnL before the trade and after the trade for each trader.

Something like:
```
query {
  party(id:"b71715c1ebf436ff2365fed13c63c524486e4880e21b5e8a9eea035078186bb0"){
    trades{
      market{
        name
      }
      size
      buyerPnL
      sellerPnL
    }
  }
}
```
Gets:
```
{
  "data": {
    "party": {
      "trades": [
        {
          "market": {
            "name": ""
          },
          "size": "83",
          "buyerPnL": "-100",
          "sellerPnL": "+123",
        }
     }
  }
}
```

I've added Label:core-plugin-dependant assuming this is true.

**Comment by gordsport** [comment]
Closing - we have not plans to implement this feature in the medium term unless there is a real need for this
