### ISSUE TITLE
Markets query pagination/filtering

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/data-node#422]
# Feature Overview

**In order to** Avoid over fetching
**We will** Add pagination parameters to the markets query
**So that** We can fetch for only the markets we want to see

# Tasks
- [ ] Determine filter options
- [ ] Determine pagination style (limit, offset or cursor based)
- [ ] Implement pagination
- [ ] Implement filters

# Acceptance Criteria
- It is possible to query for a filtered set of markets
- It is possible to query for a paginated set of markets

**Comment by gordsport** [comment]
pagination has been implemented
