### ISSUE TITLE
TradesSubscribes does not return trades

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/data-node#428]
Have test which sets up a trade by matching two orders.
Using a function which builds a datanode TradesSubscribeRequest which is filtered by marketId and pubkey and then uses this request to return TradesSubscribe from the datanode.

This never returns anything even though trades are created by the core.

**Comment by gordsport** [comment]
@vega-paul 
 In a brief triage of this it looks like data-node v2 is returning the trades. Can you please check this and close if no longer an issue?

**Comment by gordsport** [comment]
closing as fixed
