### ISSUE TITLE
Plugin request for historical account balance API (Insurance Pool etc)

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/data-node#43]
In GitLab by @cdm on Jan 20, 2020, 17:46

BACKGROUND:

This ticket: https://gitlab.com/vega-protocol/trading-core/issues/640

THOUGHTS:

This could maybe be generalised to be an account balance history API/Plugin? Would need to to discuss.

MOTIVATION:

Add a historical insurance pool value that we can use to produce a sparkline, similar to the candle data 

uses the Candles data to generate the 24h charts, so data in that same shape would be great.

**Comment by gordsport** [comment]
The history of balance accounts has been implemented

**Comment by edd** [comment]
https://github.com/vegaprotocol/vega/issues/5719 - Bug raised related to this
