### ISSUE TITLE
For priceMonitoringSettings->Parameters->Trigggers return the percentile too

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/data-node#513]
At the moment price monitoring settings return 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/62546419/163567565-99d9247f-1824-4bf8-b22f-3f8adfd356de.png">
but they should also include the probability / percentile setting. 

The GraphQL is 
```
market(id:"f64a2c4c2dee02334269950db3deb5c12d818fe407e4e989e4c212021318e21b") 
{
    name
    state
    priceMonitoringSettings {
      parameters {
        triggers {
          horizonSecs
          auctionExtensionSecs
        }
      }
    }    
  }
```

**Comment by jeremyletang** [comment]
@davidsiska-vega I've just checked on the testnet playground and this seems to be available. Are you happy to close this ticket?

<img width="961" alt="Screenshot 2022-07-12 at 16 52 25" src="https://user-images.githubusercontent.com/4346460/178519643-87115e23-8789-4fc0-b281-b9a185e9b57a.png">

**Comment by gordsport** [comment]
This is now present - closing
