### ISSUE TITLE
Proposals not returning proposal rationale details

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/data-node#594]
When querying for proposals , the proposal rationale details are not being returned
```

query {
  proposal(id:"13a977aee873bc5e873db761231df3910b222a11e36c8b3be6f1d0641310b74b") {
    id
    reference
    state
    datetime
    rejectionReason
    errorDetails
    rationale {
      description
      hash
      url
    }
  }
}
```

Response

```
{
  "errors": [
    {
      "message": "must not be null",
      "path": [
        "proposal",
        "rationale"
      ]
    }
  ],
  "data": null
}
```

**Comment by ze97286** [comment]
cannot reproduce in testnet. @MuthuVega can you verify that this can be closed please? 
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/6655556/176843771-83f6aa71-ebb0-4171-ad19-9b566e350a89.png">

**Comment by MuthuVega** [comment]
Tried it again in local vega capsule env - but no luck @ze97286 
Maybe @pscott31 or @ettec can have a quick look

Assume its some issue with the rationale fields - seems to error when they are all null.

![Screenshot 2022-07-06 at 14 30 45 (2)](https://user-images.githubusercontent.com/91467655/177562092-71a6b581-ddef-489f-ba56-a84e1612809f.png)
