### ISSUE TITLE
Functions missing in REST and GQL

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/data-node#714]
# Problem encountered
I wanted to run `GetERC20MultiSigSignerAddedBundles` with REST. Unfortunately, I am not able, because this function is available on GRPC only.

# Observed behaviour
I am not able to use REST to call some functions.

# Expected behaviour
I should be able to use REST&GQL for some of the missing function.

# System response
I am not able to send request.

# Definition of Done
I am able to run `GetERC20MultiSigSignerAddedBundles` using REST.

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
closing as V2 API will have REST endpoint added
