### ISSUE TITLE
Datanode seems to be ignoring reward events when restarting from epoch

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/data-node#726]
Rewards not showing in the datanode until the 2nd epoch after a checkpoint restart (seen in 0.50.3 in mainnet)

suspected that it is related to the loading for checkpoint yesterday where the events are somehow ignored by data node

**Comment by ze97286** [comment]
this is a core issue not datanode - https://github.com/vegaprotocol/vega/issues/5514
