### ISSUE TITLE
Check scripts in script folder

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/data-node#760]
Seems like we have a lot of scripts in the scripts folder which are most likely unnecessary (i.e: multi architecture build with cgo, while all the codebase is building without CGO...)

Let's try to reduce these scripts to a mininal, or even completely remove them, we should be able to build anything with just `go build / go install`.

**Comment by jeremyletang** [comment]
cc @fkondej you may know if these scripts are of any use anywhere.

**Comment by gordsport** [comment]
Script folder has been removed during the move back to vega repo
