### ISSUE TITLE
Unable to retrieve key rotation transactions from datanode

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/data-node#772]
Running the below query in data node brings back no results

```
query {
  keyRotations {
    oldPubKey
    nodeId
    newPubKey
  }
}
```

Response

```
{
  "data": {
    "keyRotations": null
  }
}
```

However , a key rotation transaction was successfully processed and below is the event produced.

`{"id":"104-8","block":"BC36826FF96C4AADAC4EF01C5ED786806754948F6B012B8BF52D767F61F6998E","type":"BUS_EVENT_TYPE_KEY_ROTATION","keyRotation":{"nodeId":"7be4b6555c345a73eb3344adf993590bc8c7eeaf58138511eb14b4b236432fe7","oldPubKey":"603fdaa7f695a519a427308f7e44860d63620d1e0347fab8c836f7b4ad5275b0","newPubKey":"4561e640b41673c038aee7b9b5cd497efbae805ceefea2359f052496dcab7182","blockHeight":"104"},"version":1,"chainId":"test-chain-dT4I9w"}`

**Comment by gordsport** [comment]
Hey @MuthuVega 
- https://github.com/vegaprotocol/vega/issues/5673
Is this a duplicate?
