### ISSUE TITLE
party marginConnections and party positions marginConnections both raises errors

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/data-node#849]
# Problem encountered
When running below query on testnet (https://lb.testnet.vega.xyz/playground)

 
```
query Positions($partyId: ID!) {
  party(id: $partyId) {
    marginsConnection {
      edges {
        node {
          initialLevel
        }
      }
    }
    positionsConnection {
      edges {
        node {
          marginsConnection {
            edges {
              node {
                initialLevel
              }
            }
          }
        }
      }
    }
  }
}
```

```
{"partyId": "02eceaba4df2bef76ea10caf728d8a099a2aa846cced25737cccaa9812342f65"}
```

# Observed behaviour
I receive error
```
failed to make edge for {1108 15618114 17179925 39045285 42168907 2022-08-12 13:29:35.930284 +0000 UTC 2022-08-12 13:29:35.930284 +0000 UTC}: expected account source argument, got:[0xc000554600]
```

# Expected behaviour

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Go to https://lb.testnet.vega.xyz/playground
2. Run provided query

# Evidence

![image](https://user-images.githubusercontent.com/1754247/184364188-0db4e986-01df-43b3-b9fb-560ae0c0edf1.png)

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by guoguojin** [comment]
This was fixed in https://github.com/vegaprotocol/data-node/pull/830
