### ISSUE TITLE
Market candlesConnection returns null and raise error

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/data-node#853]
# Problem encountered
When running below query on testnet (https://api.n01.stagnet3.vega.xyz/graphql/)

```
query Market($marketId: ID!, $interval: Interval!, $since: String!) {
    market(id: $marketId) {
      id
      tradingMode
      state
      decimalPlaces
      positionDecimalPlaces
      data {
        market {
          id
        }
        auctionStart
        auctionEnd
        markPrice
        indicativeVolume
        indicativePrice
        suppliedStake
        targetStake
        bestBidVolume
        bestOfferVolume
        bestStaticBidVolume
        bestStaticOfferVolume
        trigger
      }
      tradableInstrument {
        instrument {
          id
          name
          code
          metadata {
            tags
          }
          product {
            ... on Future {
              oracleSpecForTradingTermination {
                id
              }
              quoteName
              settlementAsset {
                id
                symbol
                name
                decimals
              }
            }
          }
        }
      }
      marketTimestamps {
        open
        close
      }
      candlesConnection(interval: $interval, since: $since) {
      	edges {
          node {
         		open
            close
            volume   
          }
        }        
      }
    }
  }
```

`{ "marketId": "32654516ed4ba18a25c9bc986d3686f64db7ea353ecf6b503d12bf32bb7fe6a8", "interval": "INTERVAL_I1H", "since": "2022-09-15T06:41:10.000Z" }`

# Observed behaviour
Below error is returned
`could not find candle for market 32654516ed4ba18a25c9bc986d3686f64db7ea353ecf6b503d12bf32bb7fe6a8 and interval INTERVAL_I1H`

Market `candlesConnection` has null value

# Expected behaviour
candlesConnection should return data, no errors should be raised

# Evidence
![image](https://user-images.githubusercontent.com/1754247/190605709-fd6aab13-ff96-434c-8220-be81a263c96a.png)

**Comment by gordsport** [comment]
Hey @bglownia 
A number of fixes around the candles APIs have gone into stagnet3. 

Please can you check these out:

- https://github.com/vegaprotocol/vega/pull/6079
- https://github.com/vegaprotocol/vega/pull/6135
- https://github.com/vegaprotocol/vega/pull/6173

And the changes on FE side:
- https://github.com/vegaprotocol/frontend-monorepo/pull/1324
- https://github.com/vegaprotocol/frontend-monorepo/pull/1330

And if you think related try testing this in stagnet3?

**Comment by guoguojin** [comment]
I think this is actually a valid bug because the handler doesn't map the interval correct back to the format used in data-node v2. I'm got a small patch coming that fixes this mapping and should resolve the bug.
